spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3310/jpaTest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jesusisking


  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

