### Send POST request with json body
POST localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "FULL_STACK",
  "experienceYears": 2,
  "memberId": "12jesusisking",
  "name": "kyukin33",
  "age": 18
}
