### Send POST request with json body
POST localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 10,
  "memberId": "jesusisking",
  "name": "kyukin33",
  "age": 27
}
