### Send PUT request with json body
PUT http://localhost:8080/developer/jesusisking
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 13
}
