version: '3'

services:
  mysql:
    container_name: queryDsl_mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: jik
      MYSQL_PASSWORD: jesusisking
      MYSQL_DATABASE: querydsl_test
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"